function clearResults() {
  Equip.value = "";
  totFAr.value = "";
  NB.value = "";
  TGY.value = "";
  LD.value = "";
  OT.value = "";
  FCP.value = "";
  TBOT.value = "";
  TBFC.value = "";
  TBR.value = "";
  TGR.value = "";
  document.getElementById("FCr").setAttribute("height", 0);
  document.getElementById("TRr").setAttribute("height", 0);
  document.getElementById("TCr").setAttribute("height", 0);
  document.getElementById("NRr").setAttribute("height", 0);
  document.getElementById("BEr").setAttribute("height", 0);
  document.getElementById("PBr").setAttribute("height", 0);
  document.getElementById("TPCr").setAttribute("height", 0);
  document.getElementById("TVCr").setAttribute("height", 0);
  document.getElementById("TVCt").setAttribute("fill", "#FFC82E");
  document.getElementById("TFCt").setAttribute("fill", "#FFC82E");
  document.getElementById("TPCt").setAttribute("fill", "#FFC82E");
  TotRev.value = "";
  TSC.value = "";
  TFRC.value = "";
  TCC.value = "";
  THC.value = "";
  TBC.value = "";
  TotFuC.value = "";
  TLC.value = "";
  TBTC.value = "";
  THI_I.value = "";
  LRC.value = "";
  TFC.value = "";
  RMC.value = "";
  FCLC.value = "";
  TBTCv.value = "";
  TVC.value = "";
  TotPC.value = "";
  TotFC.value = "";
  TotVC.value = "";
  TC.value = "";
  TRAC.value = "";
  TCAC.value = "";
  NP.value = "";
  NPAC.value = "";
  BE.value = "";
  EqTyp_ABP.value = "";
  PB_ABP.value = "";
  ROI_ABP.value = "";
  EqTyp.value = "";
  PB.value = "";
  ROI.value = "";
  HCC.value = "";
  HCCPc.value = "";
  HCCPAc.value = "";
  CICa.value = "";
  HC.value = "";
  BL.value = "";
  TPC.value = "";
  SC.value = "";
  FRC.value = "";
  CC.value = "";
  CIC.value = "";
  Dep.value = "";
  THI.value = "";
  INT.value = "";
  TFC.value = "";
  RMC.value = "";
  // FC.value = "";
  // LC.value = "";
  TVC.value = "";
  TotPC.value = "";
  TotVC.value = "";
  TotFC.value = "";
  TRAC.value = "";
  TCAC.value = "";
  TC.value = "";
  NP.value = "";
  NPAC.value = "";
  BE.value = "";
  PB.value = "";
  ROI.value = "";
  NCNR.value = "";
  NCPB.value = "";
  NCROI.value = " ";
}
