function toggleSwitch() {
  var remember = document.getElementById("switch").checked
  if (remember == false) {
    FieldAreaUnit.innerHTML = "(ac)"
    minAr.value = 20;
    maxAr.value = 640;
    Ar.min = 20;
    Ar.max = 640;
    ForYldUni.innerHTML = "(lb/ac)";
    minBy.value = 500;
    maxBy.value = 50000;
    By.min = 500;
    By.max = 50000;
    By.step = 100;
    BalMasUni.innerHTML = "(lb)";
    minBm.value = 800;
    maxBm.value = 2000;
    Bm.min = 800;
    Bm.max = 2000;
    FldRntUni.innerHTML = "(FAR, $/ac)";
    SdCstUni.innerHTML = "(SC, $/ac)";
    FertCstUni.innerHTML = "(FRC, $/ac)";
    ChmCstUni.innerHTML = "(CC, $/ac)";
    HrvCstUni.innerHTML = "(HC, $/ac)";
    BlCstUni.innerHTML = "(BC, $/ac)";
    FlCstUni.innerHTML = "(FC, $/gal)";
    TrcSpdUni.innerHTML = "(mph)";
    minSp.value = 4;
    maxSp.value = 8;
    Sp.min = 4;
    Sp.max = 8;
    BlTrnsCstUni.innerHTML = "(BTC, $/mile)";
    BlTrsnDisUni.innerHTML = "(BTD, mile)";
    ArResUni.innerHTML = "(ac)";
    LogDisResUni.innerHTML = "(mi)";
    BlColFuUni.innerHTML = "(gal)";
    TotBlFuUni.innerHTML = "(gal)";
    // document.getElementById("TotRevUni").innerHTML = "Total revenue per acre:"
  } else {
    FieldAreaUnit.innerHTML = "(ha)"
    minAr.value = 8
    maxAr.value = 259
    Ar.min = 8
    Ar.max = 259
    ForYldUni.innerHTML = "(Mg/ha)"
    minBy.value = 3
    maxBy.value = 56
    By.min = 3
    By.max = 56
    By.step = 0.5
    BalMasUni.innerHTML = "(kg)"
    minBm.value = 350
    maxBm.value = 950
    Bm.min = 350
    Bm.max = 950
    FldRntUni.innerHTML = "(FAR, $/ha)"
    SdCstUni.innerHTML = "(SC, $/ha)"
    FertCstUni.innerHTML = "(FRC, $/ha)"
    ChmCstUni.innerHTML = "(CC, $/ha)"
    HrvCstUni.innerHTML = "(HC, $/ha)"
    BlCstUni.innerHTML = "(BC, $/ha)"
    FlCstUni.innerHTML = "(FC, $/L)"
    TrcSpdUni.innerHTML = "(kmph)"
    minSp.value = 6
    maxSp.value = 15
    Sp.min = 6
    Sp.max = 15
    BlTrnsCstUni.innerHTML = "(BTC, $/km)"
    BlTrsnDisUni.innerHTML = "(BTD, km)"
    ArResUni.innerHTML = "(ha)"
    LogDisResUni.innerHTML = "(km)"
    BlColFuUni.innerHTML = "(L)"
    TotBlFuUni.innerHTML = "(L)"
    // document.getElementById("TotRevUni").innerHTML = "Total revenue per hectare:"
  }
}